config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :web
  root :to => 'web#index'
  get 'webs/:id' => 'web#show'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :site
end

app/models/site.rb
class Site < ActiveRecord::Base
  mount_uploader :image_url, ImageUploader
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web_controller.rb
class WebController < ApplicationController

  def index
    @site = Site.order("created_at DESC").page(params[:page]).per(5)
    @categories = Category.all
  end

  def show
    @categories = Category.all
    @category = Category.where(id: params[:id])
    @site = Site.order("created_at DESC").page(params[:page]).per(5).where(category_id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_helper.rb
module WebHelper
  def br(str)
    h(str).gsub(/(\r\n?)|(\n)/,"<br />").html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductTrip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap core CSS -->
  <!--   <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--     <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
<!--     <link href="offcanvas.css" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
<!--     <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header kimu">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand tittle" href="/">ProductTrip</a>
        <!-- <div class="tittlebox"><a class="tittle col-xs-12" href="/">ProductTrip<h6 class="subtittle hidden-xs">- 革新的なWEBサービスはあなたの生活を変える -</h6></a></div> -->
<!--         <div class="tittlebox" href="/"> -->
        <h6 class="subtittle hidden-xs">- 革新的なウェブサービスはあなたの生活を変える -</h6>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav kimura">
          <% @categories.each do |category| %>
          <li><%= link_to "#{category.name}",web_path(category.id),class:"kimura" %></li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->

      <%= yield %>

</div>
<hr>
<footer>
  <p>&copy; 2016 ウェブサービス紹介サイト「ProcuctTrip」</p>
</footer>

</body>
</html>

app/views/web/_site.html.erb
      <div class="jumbotron">
        <h4 class="font"><%= site.name %></h4>
        <% site.text %>
        <div class="image-box col-sm-6">
          <img class="image col-xs-12 col-sm-12" src="<%= site.image_url %>" alt="<%= site.name %>">
        </div>
        <div class="col-sm-6 textbox">
        <h4 class="url"><%= link_to site.site_url,"#{site.site_url}", :target=>["_blank"] %></h4>
        <p class="acMenu detail">詳細を見る</p>
        <div id="slideBox">
          <p class="text font"><%= simple_format(site.text)%></p>
<!-- <iframe src=<%= site.text %>></iframe> -->
        </div>
        </div>
      </div>

app/views/web/index.html.erb
  <div class="tittle-image">
    <%= image_tag "top_image2.jpg", class:"top_image visible-sm visible-md visible-lg" %>
    <h3 class="phrase visible-sm visible-md visible-lg">革新的なウェブサービスはあなたの生活を変える</h3>
  </div>
  <div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs location">
            <!-- <button type="button" class="btn btn-success btn-xs" data-toggle="offcanvas">カテゴリー選択</button> -->
          </p>
          <h3 class="category">カテゴリー：全て</h3>
          <%= render partial:"site", collection: @site %>
          <div class="page"><%= paginate(@site) %></div>
        </div><!--/.col-xs-12.col-sm-9-->
        <div class="col-sm-3 hidden-xs sidebar-offcanvas side-category" id="sidebar">
          <div class="list-group">
            <% @categories.each do |category| %>
            <%= link_to "#{category.name}",web_path(category.id),class:"list-group-item" %>
            <% end %>
          </div>
        </div><!--/.sidebar-offcanvas-->
    </div><!-- /.row -->
  </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

app/views/web/show.html.erb
 <div class="container">
  <div class="row row-offcanvas row-offcanvas-right main">
  <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs location">
        <!-- <button type="button" class="btn btn-success btn-xs" data-toggle="offcanvas">カテゴリー選択</button> -->
      </p>
      <% @category.each do |category| %>
      <h3 class="category">カテゴリー：<%= category.name %></h3>
      <% end %>
      <%= render partial:"site", collection: @site %>
      <h4 class="page"><%= paginate(@site) %></h4>
    </div><!--/.col-xs-12.col-sm-9-->
    <div class="col-sm-3 hidden-xs sidebar-offcanvas" id="sidebar">
      <div class="list-group">
        <% @categories.each do |category| %>
        <%= link_to "#{category.name}",web_path(category.id),class:"list-group-item" %>
        <% end %>
      </div>
    </div><!--/.sidebar-offcanvas-->
  </div><!-- /.row -->
  </div><!-- /.container -->